[servercfg]
ip = "127.0.0.1"
port = 8080
db_url = "postgres://app_user:app_user@localhost/miniprogram"
redis_url = "redis://127.0.0.1:6379/"

[tokencfg]
access_token_ttl = 20
refresh_token_ttl = 40

access_prikey = """
-----BEGIN RSA PRIVATE KEY-----
MIIJJgIBAAKCAgBSmkhmd8Z+XHQ99rJukPtsu7V46QCpIk6g5+pn6xyxIpx/2NR7
l6IyVUlCuncANDpn0rJhF/MweKc4L2ExVu4e86CE7zoYIUhGPytD7Ww75o6V3Eyn
ij7cUKGSFHP1sr4CilnGHhr9U/j0+1PdB8FPvyLpWqTcEMu1BeUFvKg3HbAZfdtG
ZQcgPdl7E0tAbDF2JmPnPwzsjiUkiU4IBNUBNxWOjpbQAuaAvpb2dkXDtQHPCate
CtRfGrzW81EYHG76K5p/+5FXjw8VPrEBY+DdZHcDYdDOsBPE2dPeKEjm+4tt+250
em7X0kwwYkNme4mqFLdlMB2o1d8iSmjD53Qa8RJ4ZWqpPn+f24O/+lhUKGbubV8v
ItReSuzmbW6x6k6tgNW1B2KpaVFg0x6vhxCUFnjZRGUZ7NkxGub6aoby8sozXJq6
JkcwxxqxMdX3m5B0pVJttNcPVtXVh/MjYPCH1HovRZYr+FQrFgjKfk0B6vygC3CN
mtovPCe63b5JI0xvDbeiYe6RrTVaS69EkoCIk/53QYIQs7mWuB8nlY2mVs4BKnLQ
3K/m4t9dZhizCCZwVjGDmLiGQvTU0JIiGjs0aypAVrzipUoWZbQJWQhMtuugxoRX
vu7dkBHsJi+vg0TBsKsSOWXciaKVbrATaGgiwwkaKxb+bvELtQV25Q1wHwIDAQAB
AoICAB6YnSavSOu3LStifHct5qNA6BgQHjmHxp4dKRsy4B7Qli1Y0GOzJ9YC9y7r
SHbf4Z5hUcdbCq4ykqXiDtsquurmDNgQkHEtqsqyTUFM6SFK5hemURJhx6TtjNtC
Di289lqUimoy7oZVG0sK6OZfIAB86N6Mv7Hv2rSDqXA1kA1SRs86agUqGLidkDfh
TqdfK/b6g1i9ZvkcMa/V1/xqZceccrSqJjyIRn77mYlTB8ZU/oWErGAaHM3ZZocr
+ya2KXkqu4CaWxyWldylqwS7zSfUNa0gByr312q70JliTJaaJ+wmDKTCUNpKQARP
8W09ZyGDqOanKuVFyu+1phaiXcPMcD7zz2um/K6Nhr8Oqxcb5bJvCvlsBJyfH569
BaokIDyuC2a6i7HWajhuivb40xwWPgrxNcPn55KixlmMPBGr/W/SxRKhilCgIQrY
PrGHYWP7UW5k0RTih4CY9UkH8KX68hlAxO6AWhmVUM6WtFofG0eQ1+CWzk4+1uUe
15tMRg0mnzK6fNqHb2V4zBFqBzeI7XEJn0Cj9+hKjR4ytRqxf25GZkpcvTA+dHc6
nEW2NAEFKdWleACT0f5+6hLX2Fo8xVGGnwUDoTtFK0kNyVhWM8Qb8wliwGJqQGFO
u2uOXJjhay5I2irH9/2MQk6z6EcV+e9WFK339QgpvxluJBAhAoIBAQCkLLvyOsVZ
m370oiX42ptbeXStlDxVLbv3e41iLr/R6ZOc9n7FZi7Jh4Ib8VcTmMB4mLE5F8mq
rkphVsbzBOPAV7cs9ucBmYMkMFex3XN9UVgEiSWe/QTrs4usHrwnYf88PvgTQ2ix
sybrktSAOHLWsGTBdb+Qfd5zzE4YyW2WqT4uj/aLQNPtC5n8pvgecx2SjbY0A+VV
eGl3+QRqYG2yvypy5t8jGuPPFymA4Yo9H67ioPworFJu4QiOnHCawpAxJ+pMf4yd
rBQC98ctTmc7USPecnCwTp9g+r5dDrGZwBeTP+dTnGcWGXIbWqtFAWSn92FxkBue
RVuPs1S/LNvRAoIBAQCAzbK0e6AfT742OZRL0QlJUVdR3ommpDvCj8Yk8hruUtkt
jgWhqgGu9qDK/RJjBAYYixeBcIDzuQAoYQaxkR6qy4k6pqAwnevJ8EFrtOClf2U3
1G566EqP9LVGDx9c+RmapT3EnPMpWO+rwlMDCZfT1mKqcsJT0DwZymDCq8Cgi1eh
jZfOCRbJOQXFpW3kpMFXwiBH5zP+CgpZfzBiaZo5wTPm1rd4LnxTkPeNJFeZ2qv3
whCX8jz2hkeykpjE0Y1yQTUK8L7b5vS0GeR9z4kALItbeK2+JzToTyEOP8WnCSN/
SzeCk9uzxdLjzW3k4BU+RV8rW8DG6m86XhcqzrjvAoIBAHHgwcGk+I1OacKg0rwK
TuclmURp5WukHJTu88Qd71pYrdabuJWOanfJ8fsV7bOfKiq8p3mVwYIOAXQBcGDT
jHM3pMygut4GMMwiaEHs/RX5HZeP1jOxB//Ce+i5LQQYWqXce9FI2c8hGKchIxuJ
jEbU9h6nYWiFlo82MRnKZqSx4nsDyx0Oq7HqcTaqTsM4UFP+zlrINQSTUH0yktiC
6LSrG3O2JyM/nLNiOpy2VWBOoM18o0xHM6rLl1bstsLyoHgoWsITW2NnID5qxpLr
pnmjr8C2GuqArtbjNrZv4ctnTjMKiZgajfrrTZYhz1k/PSWxV7shHbcsHvXPi8JM
CHECggEAZcqqTUpaLASoTVBJ63UDAsde29ukK2clt0hKjo4rTGd7LS5NMwsZE33j
ayh/bHMUojbiV7BiqLpu7npngNMwSkhaZliixmk3m7rc6NLkqsY4ZtviiA2mR4hb
7kcrQR2352hpnUVwQiAAIVyMoBznuUl3Zj8VZoltxfATciWsMPSOR6WP8Atsz4/a
CO4JICY4ijNnsYt9ommq7jm/MjdE5BnU+7x6+Ga8aIprqUasWHHhcAcVeA+/sBBE
/1Itm3YEc+QmmEPUghNPFjpUQj1Ohy2s4JhJrrprbKCEfi9V9AEb5ZC7CN3zRmqz
lMaX78ZL44+Ne8WiX1GMn7MWWgVPTwKCAQA64f9PSKWcOsx9xkvF/YdTuwYUHtRj
sQ5NGc0dnuCa/iXc5jEfF5cGTHQn65dq3E0tSyBgC9819B7MX/6Dm4KJEw2lB2O9
+fSWjO2X6iMX6O5Wc3YmOiaZtIPqGzwKiJZclfPRRnm4OwTXou8gtu0ZwNk6mplm
uC4Flu0OqblLu8OhE6Ece3NLYETZerS5xqTPesLrFALC/7zmsa6u9Yp2eT79MykU
6gCnmbvggD5iE4jQe+NfEqDP8nihggIfGQgkGMZQH2ewNn/UeMbUk1nArdxaT65i
Rz3Gwz+Av6IGwi+s/CWJW2ScZT6bSf77W+fEH1zy++EqLXAE31oQkmW6
-----END RSA PRIVATE KEY-----
"""

access_pubkey = """
-----BEGIN PUBLIC KEY-----
MIICITANBgkqhkiG9w0BAQEFAAOCAg4AMIICCQKCAgBSmkhmd8Z+XHQ99rJukPts
u7V46QCpIk6g5+pn6xyxIpx/2NR7l6IyVUlCuncANDpn0rJhF/MweKc4L2ExVu4e
86CE7zoYIUhGPytD7Ww75o6V3Eynij7cUKGSFHP1sr4CilnGHhr9U/j0+1PdB8FP
vyLpWqTcEMu1BeUFvKg3HbAZfdtGZQcgPdl7E0tAbDF2JmPnPwzsjiUkiU4IBNUB
NxWOjpbQAuaAvpb2dkXDtQHPCateCtRfGrzW81EYHG76K5p/+5FXjw8VPrEBY+Dd
ZHcDYdDOsBPE2dPeKEjm+4tt+250em7X0kwwYkNme4mqFLdlMB2o1d8iSmjD53Qa
8RJ4ZWqpPn+f24O/+lhUKGbubV8vItReSuzmbW6x6k6tgNW1B2KpaVFg0x6vhxCU
FnjZRGUZ7NkxGub6aoby8sozXJq6JkcwxxqxMdX3m5B0pVJttNcPVtXVh/MjYPCH
1HovRZYr+FQrFgjKfk0B6vygC3CNmtovPCe63b5JI0xvDbeiYe6RrTVaS69EkoCI
k/53QYIQs7mWuB8nlY2mVs4BKnLQ3K/m4t9dZhizCCZwVjGDmLiGQvTU0JIiGjs0
aypAVrzipUoWZbQJWQhMtuugxoRXvu7dkBHsJi+vg0TBsKsSOWXciaKVbrATaGgi
wwkaKxb+bvELtQV25Q1wHwIDAQAB
-----END PUBLIC KEY-----
"""


refresh_prikey = """
-----BEGIN RSA PRIVATE KEY-----
MIIJKgIBAAKCAgEArY9n28QiavxJSPOn8G/OlUU/gYU4Uy7Idf1PtWEzpLQi2QB0
C2iR3qhUEqdliBLgaZY7IMtAqZko3SyTY8ATalijp8QJPZtBAWVWNS4K8+ZBiwPR
ovdVQikb0FkmUrry2DChSaPn2lkTrZCk+2sWc8c7Nbfp4x80sXzW2ktwDUT2vYCF
WWEHP58VXPFdNOWzyDdEtx+HnalDFeLHqWB+0tv601MPcoGf+UYPFiOJfZSig9E7
4qX4wsDHxZ6zfDDq5Nbg1rCooLuDykz52aGdVjRmzMOH1e+xQ9yWWzZqrr+FM4y3
YSgvPqPEjbcSU+C7iRfPK4zjndJ698AWN4wtXt9P7vUppjmO3ssa2jQrDzGnosis
JH8qCleyp6glwyqpJEPBHKSU0XucLJMr22EubndjSnCsxh4DYtF0XlksgD3ImqYq
1obG569/1u0tSLHSt7/6huf+j9P/t5zjjulGn4JVj3ES1e+QlfGKAOkkTsD5sWMl
CAArcMTb3adx+T5Iod06nmcileQ+F1CD3xLbZS9XYDmCJpc4vevwIdt4uVaJ/2/N
hR/B+5+NPky4p+rzm6AHtCP833uJOYhixlNEG5788tehxTxW4vdYcP9PfEpokILN
Mo7UmrsjfI1IhXGrP0FPUi3OfOVLcivrIBJ3yqO1LGpNhUBYkvDd4cC02HMCAwEA
AQKCAgEAk2aGkyuI+4mWB+H/UAD01us/2xU0V9kUoLhouKd7v7bJHbj31TSTJiGZ
fVozrZQyiRnwz5IvMZqFDQothvr6wkfTfcjM/EhdtfzFcVbQMIHuSk0M/rXF7/GP
0KvWE074rcjnQe51G4ipYK/Gnkw9fkjHLYErnxvCmbZnlm+ZE3vtfdWn6tev20WV
VCEcwq8Ot8zQjCG4AJtfAThfz6bHLvdql40kQmB6Z68rYub9fuz79K1/iabhlS06
vMhisOeupnkj7NGN9Swr6mTjkQRj5nGMmPy64WO3DeZKv96ATjcTvksU9uu07CMT
7DN92kSzoOPaq6b1LPU0QDMf6z8ey9uVjIQjNQH2t1fTUHcX6KweSpI8sYxDpgNJ
SyP66dfZQQ5F2u87lLHtPDHfOQk2nldXeFoCRnkfFaoF1BmfpNOStbeaQ69y+orH
46bkrP+wH/PUhcmIe1qG2ZVQze5pYKlXdNrORi9/v7YAXdhcuN9oFgDbPzBU3XD9
rjFwnA1dLYQADHkYavsLd6habACDHi97UDMDDxkqRNRkg+r0Ph3AEpNOpS75eWyP
Be8gkyzd+wZ9EA6ByUkW/MEq5vdbdti/k88rAsN8y76LzxUEk1xIDsT0cFKhxjVO
j6Ni8DwfYDwzeK/eqs/3yCfpLWRd3C5pyXufhTlU3u5HNuHqHikCggEBAOcrHHPx
gicDERoTgRzaHypyCNTj6s+/ACShqkRJpKWBanYmGG6oOlqp/ydGbucA8xEiTQV1
byeo7GqvbC1VFMHpNU57Ws8dkA2KJQR0PXtSS1pLu1RuJPa/DVHmWh9RR0iiHZv0
4Ym1Mlr9XqOh2hwnfD3QFPLsxDnGsMt4qAyth7yamtKxC4LUN0so8q/HMXGRdgnT
2M/M4jtmdtmWhonHoMHbQEO+nme+c30uTk7SM0Hgpr4zB1Ja8Qn4vhK/9hPvHwbq
msK7w8Bp0cIasHz2Ln3/kHE2g3PJ75bQdsA39OVXJLDketUur327U2dNKuHVgQRW
JgezMrdlYWcQPqcCggEBAMA0IPVyxO1/uVT4+mCrvHReMoptHbiJs/g0uuUP9dR8
XXQILIUKkwvx/1uNbq7XwVRV2F0R7PiZlOB2qbuPrQB4zwgRv7eAhub0Mrn6LUnX
eoWzrnwXi3cML2UuW/dFRfZbAE7ZhQvsrWV5F3GCgVG8suGAt6pvVRz/z1yD5odD
w5CzlkYKwt5g0Min8tE9TKmy6VDCQqEBUR1gkhOFjTq4wWnwJqbuwJH8oxuRF2dQ
gHZKPEp0aSr3/f3ObGrWlgRNaXtrdtBtSsY2ERglQxbs67r8Z1Wm6wERH6JpYLNp
WEdyt2Qps9eOEScePyQ3x9ADNIraj9HQ49KnfQwT/VUCggEBAKPE0gJ93UQAEzST
Dsw+5wduBD22PhrxaIuLEJISTheGiMKtGHAEtFqYxo+vgVAcRxcjYsd0O8wwC1VF
c/Dlrq/1pHM2Rs4mVnCRJspyA0CDu6h7sHoPEhbQoQIdnElFjqexWiKrqMCjYso9
Z7erKVb6zjUIXl7/R8Dat1Ne5kcdBOWj7f1Huiz0ZTvVBaFsD+YyNBqgP6BvuPJ2
E8rwrd2cVJIh3vRfbd93eF/91zJWDkQkgFyM0CoTDWKQGzAzWIUkyalfuUYuOW7u
SNEnkVLmIWfYDx91jEkSja8dfpOM0O1NAExlgXPYADGl7V9otvGJDT7iPU0FMe/l
XczjIE8CggEAYWNIe/XOUKTSDHsnqon6MGB2bWuCjrm/ZfmZ5Wzj2+m0FJH7tOG5
xmi1Qfd06MTL4eapfecSUpjHNcEKmc3gFAgipu0PXnSSZj2/4jogbnTvUQXNWHU5
pnWXIkaONMl1/LD5g/p1jqg659qmhU5iJj9dyCNHbOWCk/IOaMswqMMuOYi1kQHs
4W7e+30V7O2Jhcbwr4nu5tPa/O6stZWLDQEGh542h4kcLBx9rP8kg6XnoYhV6kf3
7dzAZrUMfEoEs2NiGjZGeq+WHr7QhJKE3v3nJ9Syq1SraNv7UnjglafAIlu/DtKO
nJ8Qk+igh8J3zS+ClQTPsLmOZnOVSeRrDQKCAQEAyT3EOE/9pxIT61wxQEomeGm0
kS1j6BDGP/oGrS63LnhsLLIGQcEG/GB0CJOjyE1PSku6pdDNVDcRXq4GyVnzom6u
6oKVhZ6j6dOI2F8OZiYCcbhGLJaQaGjC1b9YoaB0TgRboM2cBNppuXQf55tXABsZ
Yr2ylX8ETBlrEnypQ1YQbrLYoQ051Uv3unu9TTWua3Yk1tETUPhLSG51qfTrZ/Uy
sD3rvTKXuYNSioYB5anVCLGxuO6YrXUEpfVxf8EmBFQdJSKSIKuRUZ7JWkp74+WA
OD3aIyE1vKFY3lXBOgSmTJk26MI7Bza1jX9yFkKPSFSuXJY92KotRnfxmCy7cw==
-----END RSA PRIVATE KEY-----
"""

refresh_pubkey = """
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArY9n28QiavxJSPOn8G/O
lUU/gYU4Uy7Idf1PtWEzpLQi2QB0C2iR3qhUEqdliBLgaZY7IMtAqZko3SyTY8AT
alijp8QJPZtBAWVWNS4K8+ZBiwPRovdVQikb0FkmUrry2DChSaPn2lkTrZCk+2sW
c8c7Nbfp4x80sXzW2ktwDUT2vYCFWWEHP58VXPFdNOWzyDdEtx+HnalDFeLHqWB+
0tv601MPcoGf+UYPFiOJfZSig9E74qX4wsDHxZ6zfDDq5Nbg1rCooLuDykz52aGd
VjRmzMOH1e+xQ9yWWzZqrr+FM4y3YSgvPqPEjbcSU+C7iRfPK4zjndJ698AWN4wt
Xt9P7vUppjmO3ssa2jQrDzGnosisJH8qCleyp6glwyqpJEPBHKSU0XucLJMr22Eu
bndjSnCsxh4DYtF0XlksgD3ImqYq1obG569/1u0tSLHSt7/6huf+j9P/t5zjjulG
n4JVj3ES1e+QlfGKAOkkTsD5sWMlCAArcMTb3adx+T5Iod06nmcileQ+F1CD3xLb
ZS9XYDmCJpc4vevwIdt4uVaJ/2/NhR/B+5+NPky4p+rzm6AHtCP833uJOYhixlNE
G5788tehxTxW4vdYcP9PfEpokILNMo7UmrsjfI1IhXGrP0FPUi3OfOVLcivrIBJ3
yqO1LGpNhUBYkvDd4cC02HMCAwEAAQ==
-----END PUBLIC KEY-----
"""
