[servercfg]
ip = "127.0.0.1"
port = 8080
db_url = "postgres://miniprogram:passwd@localhost/miniprogram"

[tokencfg]
access_token_ttl = 120

access_prikey = """
-----BEGIN RSA PRIVATE KEY-----
MIIJJgIBAAKCAgBSmkhmd8Z+XHQ99rJukPtsu7V46QCpIk6g5+pn6xyxIpx/2NR7
l6IyVUlCuncANDpn0rJhF/MweKc4L2ExVu4e86CE7zoYIUhGPytD7Ww75o6V3Eyn
ij7cUKGSFHP1sr4CilnGHhr9U/j0+1PdB8FPvyLpWqTcEMu1BeUFvKg3HbAZfdtG
ZQcgPdl7E0tAbDF2JmPnPwzsjiUkiU4IBNUBNxWOjpbQAuaAvpb2dkXDtQHPCate
CtRfGrzW81EYHG76K5p/+5FXjw8VPrEBY+DdZHcDYdDOsBPE2dPeKEjm+4tt+250
em7X0kwwYkNme4mqFLdlMB2o1d8iSmjD53Qa8RJ4ZWqpPn+f24O/+lhUKGbubV8v
ItReSuzmbW6x6k6tgNW1B2KpaVFg0x6vhxCUFnjZRGUZ7NkxGub6aoby8sozXJq6
JkcwxxqxMdX3m5B0pVJttNcPVtXVh/MjYPCH1HovRZYr+FQrFgjKfk0B6vygC3CN
mtovPCe63b5JI0xvDbeiYe6RrTVaS69EkoCIk/53QYIQs7mWuB8nlY2mVs4BKnLQ
3K/m4t9dZhizCCZwVjGDmLiGQvTU0JIiGjs0aypAVrzipUoWZbQJWQhMtuugxoRX
vu7dkBHsJi+vg0TBsKsSOWXciaKVbrATaGgiwwkaKxb+bvELtQV25Q1wHwIDAQAB
AoICAB6YnSavSOu3LStifHct5qNA6BgQHjmHxp4dKRsy4B7Qli1Y0GOzJ9YC9y7r
SHbf4Z5hUcdbCq4ykqXiDtsquurmDNgQkHEtqsqyTUFM6SFK5hemURJhx6TtjNtC
Di289lqUimoy7oZVG0sK6OZfIAB86N6Mv7Hv2rSDqXA1kA1SRs86agUqGLidkDfh
TqdfK/b6g1i9ZvkcMa/V1/xqZceccrSqJjyIRn77mYlTB8ZU/oWErGAaHM3ZZocr
+ya2KXkqu4CaWxyWldylqwS7zSfUNa0gByr312q70JliTJaaJ+wmDKTCUNpKQARP
8W09ZyGDqOanKuVFyu+1phaiXcPMcD7zz2um/K6Nhr8Oqxcb5bJvCvlsBJyfH569
BaokIDyuC2a6i7HWajhuivb40xwWPgrxNcPn55KixlmMPBGr/W/SxRKhilCgIQrY
PrGHYWP7UW5k0RTih4CY9UkH8KX68hlAxO6AWhmVUM6WtFofG0eQ1+CWzk4+1uUe
15tMRg0mnzK6fNqHb2V4zBFqBzeI7XEJn0Cj9+hKjR4ytRqxf25GZkpcvTA+dHc6
nEW2NAEFKdWleACT0f5+6hLX2Fo8xVGGnwUDoTtFK0kNyVhWM8Qb8wliwGJqQGFO
u2uOXJjhay5I2irH9/2MQk6z6EcV+e9WFK339QgpvxluJBAhAoIBAQCkLLvyOsVZ
m370oiX42ptbeXStlDxVLbv3e41iLr/R6ZOc9n7FZi7Jh4Ib8VcTmMB4mLE5F8mq
rkphVsbzBOPAV7cs9ucBmYMkMFex3XN9UVgEiSWe/QTrs4usHrwnYf88PvgTQ2ix
sybrktSAOHLWsGTBdb+Qfd5zzE4YyW2WqT4uj/aLQNPtC5n8pvgecx2SjbY0A+VV
eGl3+QRqYG2yvypy5t8jGuPPFymA4Yo9H67ioPworFJu4QiOnHCawpAxJ+pMf4yd
rBQC98ctTmc7USPecnCwTp9g+r5dDrGZwBeTP+dTnGcWGXIbWqtFAWSn92FxkBue
RVuPs1S/LNvRAoIBAQCAzbK0e6AfT742OZRL0QlJUVdR3ommpDvCj8Yk8hruUtkt
jgWhqgGu9qDK/RJjBAYYixeBcIDzuQAoYQaxkR6qy4k6pqAwnevJ8EFrtOClf2U3
1G566EqP9LVGDx9c+RmapT3EnPMpWO+rwlMDCZfT1mKqcsJT0DwZymDCq8Cgi1eh
jZfOCRbJOQXFpW3kpMFXwiBH5zP+CgpZfzBiaZo5wTPm1rd4LnxTkPeNJFeZ2qv3
whCX8jz2hkeykpjE0Y1yQTUK8L7b5vS0GeR9z4kALItbeK2+JzToTyEOP8WnCSN/
SzeCk9uzxdLjzW3k4BU+RV8rW8DG6m86XhcqzrjvAoIBAHHgwcGk+I1OacKg0rwK
TuclmURp5WukHJTu88Qd71pYrdabuJWOanfJ8fsV7bOfKiq8p3mVwYIOAXQBcGDT
jHM3pMygut4GMMwiaEHs/RX5HZeP1jOxB//Ce+i5LQQYWqXce9FI2c8hGKchIxuJ
jEbU9h6nYWiFlo82MRnKZqSx4nsDyx0Oq7HqcTaqTsM4UFP+zlrINQSTUH0yktiC
6LSrG3O2JyM/nLNiOpy2VWBOoM18o0xHM6rLl1bstsLyoHgoWsITW2NnID5qxpLr
pnmjr8C2GuqArtbjNrZv4ctnTjMKiZgajfrrTZYhz1k/PSWxV7shHbcsHvXPi8JM
CHECggEAZcqqTUpaLASoTVBJ63UDAsde29ukK2clt0hKjo4rTGd7LS5NMwsZE33j
ayh/bHMUojbiV7BiqLpu7npngNMwSkhaZliixmk3m7rc6NLkqsY4ZtviiA2mR4hb
7kcrQR2352hpnUVwQiAAIVyMoBznuUl3Zj8VZoltxfATciWsMPSOR6WP8Atsz4/a
CO4JICY4ijNnsYt9ommq7jm/MjdE5BnU+7x6+Ga8aIprqUasWHHhcAcVeA+/sBBE
/1Itm3YEc+QmmEPUghNPFjpUQj1Ohy2s4JhJrrprbKCEfi9V9AEb5ZC7CN3zRmqz
lMaX78ZL44+Ne8WiX1GMn7MWWgVPTwKCAQA64f9PSKWcOsx9xkvF/YdTuwYUHtRj
sQ5NGc0dnuCa/iXc5jEfF5cGTHQn65dq3E0tSyBgC9819B7MX/6Dm4KJEw2lB2O9
+fSWjO2X6iMX6O5Wc3YmOiaZtIPqGzwKiJZclfPRRnm4OwTXou8gtu0ZwNk6mplm
uC4Flu0OqblLu8OhE6Ece3NLYETZerS5xqTPesLrFALC/7zmsa6u9Yp2eT79MykU
6gCnmbvggD5iE4jQe+NfEqDP8nihggIfGQgkGMZQH2ewNn/UeMbUk1nArdxaT65i
Rz3Gwz+Av6IGwi+s/CWJW2ScZT6bSf77W+fEH1zy++EqLXAE31oQkmW6
-----END RSA PRIVATE KEY-----
"""

access_pubkey = """
-----BEGIN PUBLIC KEY-----
MIICITANBgkqhkiG9w0BAQEFAAOCAg4AMIICCQKCAgBSmkhmd8Z+XHQ99rJukPts
u7V46QCpIk6g5+pn6xyxIpx/2NR7l6IyVUlCuncANDpn0rJhF/MweKc4L2ExVu4e
86CE7zoYIUhGPytD7Ww75o6V3Eynij7cUKGSFHP1sr4CilnGHhr9U/j0+1PdB8FP
vyLpWqTcEMu1BeUFvKg3HbAZfdtGZQcgPdl7E0tAbDF2JmPnPwzsjiUkiU4IBNUB
NxWOjpbQAuaAvpb2dkXDtQHPCateCtRfGrzW81EYHG76K5p/+5FXjw8VPrEBY+Dd
ZHcDYdDOsBPE2dPeKEjm+4tt+250em7X0kwwYkNme4mqFLdlMB2o1d8iSmjD53Qa
8RJ4ZWqpPn+f24O/+lhUKGbubV8vItReSuzmbW6x6k6tgNW1B2KpaVFg0x6vhxCU
FnjZRGUZ7NkxGub6aoby8sozXJq6JkcwxxqxMdX3m5B0pVJttNcPVtXVh/MjYPCH
1HovRZYr+FQrFgjKfk0B6vygC3CNmtovPCe63b5JI0xvDbeiYe6RrTVaS69EkoCI
k/53QYIQs7mWuB8nlY2mVs4BKnLQ3K/m4t9dZhizCCZwVjGDmLiGQvTU0JIiGjs0
aypAVrzipUoWZbQJWQhMtuugxoRXvu7dkBHsJi+vg0TBsKsSOWXciaKVbrATaGgi
wwkaKxb+bvELtQV25Q1wHwIDAQAB
-----END PUBLIC KEY-----
"""