version: "3"
name: miniprogram
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
